
trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:

- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build First Job
  - job: SecondJob
    steps:
    - bash: echo Build Second Job

- stage: DevDeploy
  jobs:
  - job: DevDeployJob1
    steps:
    - bash: echo DevDeploy First Job
  - job: DevDeployJob2
    steps:
    - bash: echo DevDeploy Second Job

- stage: QADeploy
  jobs:
  - job: QADeployJob1
    steps:
    - bash: echo QADeploy First Job
  - job: QADeployJob2
    steps:
    - bash: echo QADeploy Second Job

- stage: ProdDeploy
  jobs:
  - job: ProdDeployJob
    steps:
    - bash: echo Prod Deploy Job



